"""add colum to free

Revision ID: 06fc859a6f3f
Revises: cc93c4d730bb
Create Date: 2025-10-03 20:21:48.615649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fc859a6f3f'
down_revision = 'cc93c4d730bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('free', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('free', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
