"""update table pocketmoney

Revision ID: 0a1f010b8c8d
Revises: bdf22e077800
Create Date: 2025-10-10 21:53:10.811429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1f010b8c8d'
down_revision = 'bdf22e077800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketmoney', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_pocketmoney_exp_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_pocketmoney_exp_id', 'expenses', ['exp_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketmoney', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_pocketmoney_exp_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pocketmoney_exp_id'), 'expenses', ['user_id'], ['id'])
        batch_op.drop_column('exp_id')

    # ### end Alembic commands ###
