"""update table pocketmoney

Revision ID: 2c9bdb26ae6f
Revises: 4fa56554f33a
Create Date: 2025-10-10 21:32:33.496942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9bdb26ae6f'
down_revision = '4fa56554f33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketmoney', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pocketmoney_user_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_pocketmoney_user_id', 'expenses', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketmoney', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pocketmoney_user_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_pocketmoney_user_id'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
