"""insert

Revision ID: 7d828e0dc55a
Revises: 0a1f010b8c8d
Create Date: 2025-10-13 20:32:06.502707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d828e0dc55a'
down_revision = '0a1f010b8c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketmoney', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pocketmoney_exp_id'), type_='foreignkey')
        batch_op.drop_column('exp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketmoney', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_pocketmoney_exp_id'), 'expenses', ['exp_id'], ['id'])

    # ### end Alembic commands ###
