"""add column to income

Revision ID: 85412d4dbd60
Revises: 8d6d6a9c9afb
Create Date: 2025-10-04 20:10:23.672222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85412d4dbd60'
down_revision = '8d6d6a9c9afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(precision=100, asdecimal=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
