"""update table pocketmoney

Revision ID: 8d1fafd9a912
Revises: 2c9bdb26ae6f
Create Date: 2025-10-10 21:36:21.365921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1fafd9a912'
down_revision = '2c9bdb26ae6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_expenses_user_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_expenses_user_id', 'user', ['exp_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_expenses_user_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_expenses_user_id'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('exp_id')

    # ### end Alembic commands ###
