"""add column to income

Revision ID: 8d6d6a9c9afb
Revises: b0a6fe8b456e
Create Date: 2025-10-04 20:06:15.821140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6d6a9c9afb'
down_revision = 'b0a6fe8b456e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.drop_column('date')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_column('year')
        batch_op.drop_column('month')

    # ### end Alembic commands ###
